language: java
sudo: false
install: true

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - mvn -f ./pwa-backend/pom.xml clean test cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
