language: java
sudo: required
# https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
  # https://docs.travis-ci.com/user/encrypting-files/#Encrypting-multiple-files
  - openssl aes-256-cbc -K $encrypted_9e617b653ae9_key -iv $encrypted_9e617b653ae9_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - cp secrets/app.properties pwa-backend/src/main/java/app.properties
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install -y kubectl google-cloud-sdk google-cloud-sdk-app-engine-java

before_script:
  - gcloud auth activate-service-account "travis-ci@growbit-0.iam.gserviceaccount.com" --key-file=secrets/travis-cigrowbit-52554fcb00cd.json
  - gcloud config set project growbit-0

script:
  - mvn -f ./pwa-backend/pom.xml clean test cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)
  # https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
  - if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then mvn appengine:deploy; fi

notifications:
  email: false
